package com.kraftfoods.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Kraft Recipe Web Service (version 1.0c)
 *
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-08T10:29:00.329+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "Kraft_x0020_Recipe_x0020_Web_x0020_Service", 
                  wsdlLocation = "http://www.kraftfoods.com/ws/RecipeWS.asmx?WSDL",
                  targetNamespace = "http://www.kraftfoods.com/ws/") 
public class KraftX0020RecipeX0020WebX0020Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.kraftfoods.com/ws/", "Kraft_x0020_Recipe_x0020_Web_x0020_Service");
    public final static QName KraftX0020RecipeX0020WebX0020ServiceSoap = new QName("http://www.kraftfoods.com/ws/", "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceSoap");
    public final static QName KraftX0020RecipeX0020WebX0020ServiceSoap12 = new QName("http://www.kraftfoods.com/ws/", "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceSoap12");
    public final static QName KraftX0020RecipeX0020WebX0020ServiceHttpGet = new QName("http://www.kraftfoods.com/ws/", "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceHttpGet");
    public final static QName KraftX0020RecipeX0020WebX0020ServiceHttpPost = new QName("http://www.kraftfoods.com/ws/", "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("http://www.kraftfoods.com/ws/RecipeWS.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KraftX0020RecipeX0020WebX0020Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.kraftfoods.com/ws/RecipeWS.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public KraftX0020RecipeX0020WebX0020Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KraftX0020RecipeX0020WebX0020Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KraftX0020RecipeX0020WebX0020Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public KraftX0020RecipeX0020WebX0020Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KraftX0020RecipeX0020WebX0020Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KraftX0020RecipeX0020WebX0020Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceSoap
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceSoap")
    public KraftX0020RecipeX0020WebX0020ServiceSoap getKraftX0020RecipeX0020WebX0020ServiceSoap() {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceSoap, KraftX0020RecipeX0020WebX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceSoap
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceSoap")
    public KraftX0020RecipeX0020WebX0020ServiceSoap getKraftX0020RecipeX0020WebX0020ServiceSoap(WebServiceFeature... features) {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceSoap, KraftX0020RecipeX0020WebX0020ServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceSoap
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceSoap12")
    public KraftX0020RecipeX0020WebX0020ServiceSoap getKraftX0020RecipeX0020WebX0020ServiceSoap12() {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceSoap12, KraftX0020RecipeX0020WebX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceSoap
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceSoap12")
    public KraftX0020RecipeX0020WebX0020ServiceSoap getKraftX0020RecipeX0020WebX0020ServiceSoap12(WebServiceFeature... features) {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceSoap12, KraftX0020RecipeX0020WebX0020ServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceHttpGet
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceHttpGet")
    public KraftX0020RecipeX0020WebX0020ServiceHttpGet getKraftX0020RecipeX0020WebX0020ServiceHttpGet() {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceHttpGet, KraftX0020RecipeX0020WebX0020ServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceHttpGet
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceHttpGet")
    public KraftX0020RecipeX0020WebX0020ServiceHttpGet getKraftX0020RecipeX0020WebX0020ServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceHttpGet, KraftX0020RecipeX0020WebX0020ServiceHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceHttpPost
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceHttpPost")
    public KraftX0020RecipeX0020WebX0020ServiceHttpPost getKraftX0020RecipeX0020WebX0020ServiceHttpPost() {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceHttpPost, KraftX0020RecipeX0020WebX0020ServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KraftX0020RecipeX0020WebX0020ServiceHttpPost
     */
    @WebEndpoint(name = "Kraft_x0020_Recipe_x0020_Web_x0020_ServiceHttpPost")
    public KraftX0020RecipeX0020WebX0020ServiceHttpPost getKraftX0020RecipeX0020WebX0020ServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(KraftX0020RecipeX0020WebX0020ServiceHttpPost, KraftX0020RecipeX0020WebX0020ServiceHttpPost.class, features);
    }

}
